# Stage 1
FROM node:10-alpine as build-deps

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json /app/
RUN npm install

COPY frontend /app/
COPY envs/prod.env /app/.env
RUN npm run build

# Stage 2
FROM nginx:1.15-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.prod.conf /etc/nginx/nginx.conf
COPY --from=build-deps /app/dist/ /dist/

CMD ["nginx", "-g", "daemon off;"]