# Stage 1
FROM node:10-alpine as build-deps

WORKDIR /app

COPY frontend /app/
COPY envs/prod.env /app/.env
RUN npm install && npm run build

# Stage 2
FROM nginx:1.17-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.prod.conf /etc/nginx/nginx.conf
COPY nginx/ssl/*.* /etc/ssl/
RUN mv /etc/ssl/app.key /etc/ssl/private
COPY --from=build-deps /app/dist/ /dist/

CMD envsubst '$DOMAIN' < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'
